# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "asciidoctor_job"
  asciidoctor_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build AsciiDoctor
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v4
      # Output command using asciidoctor-action
      - name: Build AsciiDoc step
        id: documents
        uses: Analog-inc/asciidoctor-action@master
        with:
          shellcommand: "asciidoctor-pdf -a scripts=cjk -a pdf-theme=default-with-fallback-font docs/resume.adoc -D dist"
      # Use the output from the documents step
      - name: Save AsciiDoc step
        uses: actions/upload-artifact@v3
        with:
          name: Output-document
          path: ./dist/
